config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  root 'posts#index', as: 'home'
  root to: "home#index"
  get 'about' => "pages#about", as: "about"
  patch "/posts/:id/like", to: "posts#dislike", as: "dislike"
  resources :posts do 
    resources :comments
  end
  resources :conversations do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
	belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
	has_many :messages, dependent: :destroy
	validates_uniqueness_of :sender_id, :scope => :recipient_id
	scope :between, -> (sender_id,recipient_id) do
		  where("(conversations.sender_id = ? AND conversations.recipient_id =?)
		  OR (conversations.sender_id = ? AND conversations.recipient_id =?)",
		   sender_id,recipient_id, recipient_id, sender_id)
	end
  end

app/models/dislike.rb
class Dislike < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :conversation
	belongs_to :user
	validates_presence_of :body, :conversation_id, :user_id
	def message_time
	  created_at.strftime("%m/%d/%y at %l:%M %p")
	end
  end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :dislikes, dependent: :destroy
	has_many :users_disliked, through: :dislikes, source: :user
	validates :title, presence: true,
						length: {minimum: 3}
	has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :dislikes
  has_many :posts_disliked, through: :dislikes, source: :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		body = comment_params[:body]
		username = current_user.username
		@comment = @post.comments.create({:body => body, :username => username})
		redirect_to post_path(@post)
	end
	
	def destroy
		@post = Post.find(params[:id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy	
		redirect_to posts_path(@post)
	end

	private def comment_params
		params.require(:comment).permit(:body)
	end	 
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!
  
	def index
	  @users = User.all
	  @conversations = Conversation.all
	end
  
	def create
	  if Conversation.between(params[:sender_id], params[:recipient_id]).present?
		@conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
	  else
		@conversation = Conversation.create!(conversation_params)
	  end
	  redirect_to conversation_messages_path(@conversation)
	end
  
	private def conversation_params
	  params.permit(:sender_id, :recipient_id)
	end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action do
		@conversation = Conversation.find(params[:conversation_id])
	end

	def index
		@messages = @conversation.messages
		@message = @conversation.messages.new
	end
	
	def new
		@message = @conversation.messages.new
	end

	def create
		@message = @conversation.messages.new(message_params)
		if @message.save
			redirect_to conversation_messages_path(@conversation)
		end
	end

	private def message_params
		params.require(:message).permit(:body, :user_id)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@title = "About us"
		@content = 'Created by: Sebastian Reyes, Adina Chen, Andrew Chen, Amy Doo, and Winnie Wu. '
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user = current_user
		if(@post.save)
			redirect_to @post
		else
			render 'new'
		end
	end
	
	def update
		@post = Post.find(params[:id])		
		if(@post.update(post_params))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def edit
		@post = Post.find(params[:id])		
	end

	def destroy
		@post = Post.find(params[:id])	
		@post.destroy	
		redirect_to posts_path
	end

	def dislike
		@post = Post.find(params[:id])
		if (current_user != nil)
			@dislike = Dislike.where(user: current_user, post: @post).first_or_create
		end
		redirect_to posts_path
	end

	private def post_params
		#params.require(:post).permit(:title, :body)
		params.require(:post).permit(:title, :body, :photo)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
	<p>
		<strong>
			<%= comment.username %>
		</strong>: 
		<%= comment.body %>
		<%= link_to '[X]', [comment.post, comment], 
					method: :delete,
					data: { confirm: "Do you want to delete this comment?" } %>
	<p>
<% end %>

app/views/comments/_form.html.erb
<% if signed_in? %>
	<h3>Add Comment</h3>
	<%= form_for([@post, @post.comments.build]) do |f| %>
		

		<p>
			<%= f.label :body %><br>
			<%= f.text_area(:body, {:class => 'form-control'}) %>	
		</p>

		<p>
			<%= f.submit({:class => 'btn btn-primary'}) %>
		</p>
	<% end %>
<% else %>
	<h5>Must be logged in to add comments </h5>
<% end %>

app/views/conversations/index.html.erb
<style>
.glyphicon {
  float: right;
  margin-top: 2px;
  margin-right: -6px;
}
</style>
<h1>My Inbox</h1>
<br>
<div class="panel panel-default">
  <div class="col-lg-6">
    <div id="mail">
      <h2 class="panel-heading">All Conversations:</h2>
      <div class="panel-body">
        <div class="item">
        <% @conversations.each do |conversation| %>
        <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
          <% if conversation.sender_id == current_user.id %>
            <% recipient = User.find(conversation.recipient_id) %>
          <% else %>
            <% recipient = User.find(conversation.sender_id) %>
          <% end %>
            <h5><%= link_to recipient.email, conversation_messages_path(conversation)%></h5>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
    <div id="new">
      <div class="panel-body">
      <br>
        <h2 class="panel-heading">All Users:</h2>
          <div class="item">
          <% @users.each do |user| %>
            <% if user.id != current_user.id %>
              <h5><%= link_to user.email,
                conversations_path(sender_id: current_user.id, recipient_id: user.id), method: "post"%></h5>
            <% end %>
          <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fa19Proj2TeamB</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-expand navbar-light bg-light">
      <a class="navbar-brand" href="#">Social Network</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample02">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active"><%= link_to "Home", home_path, :class =>
				'btn btn-light' %></li>
          <li class="nav-item active"><%= link_to "About", about_path, :class =>
				  'btn btn-light' %></li>
        </ul>

        <% if user_signed_in? %>
          <div style="padding-right: 10px" class="info">
              Logged in as <strong><%= current_user.username %> </strong>
          </div>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to "Conversations", conversations_path, :class =>
              'btn btn-light' %></li>
          </ul>
          <div style="padding-right: 10px">
            <%= link_to 'Edit profile ', edit_user_registration_path, :class =>
          'btn btn-light' %>
          </div>
          <div style="padding-right: 10px">
            <%= link_to "Logout ", destroy_user_session_path, method: :delete, :class =>
              'btn btn-light' %>
          </div>     
          <ul class="nav navbar-light navbar-right">
            <li class="nav-item"><%= link_to "Create Post", new_post_path, :class =>
				      'btn btn-light' %></li>
          </ul>
        <% else %>
          <div style="padding-right: 10px">
            <%= link_to "Sign up", new_user_registration_path, :class =>
              'btn btn-light' %>
          </div>
          <div style="padding-right: 10px">
            <%= link_to "Login", new_user_session_path, :class =>
              'btn btn-light' %>
          </div>
        <% end %>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/index.html.erb
<style>
  .icon-flipped {
  transform: scaleX(-1);
  -moz-transform: scaleX(-1);
  -webkit-transform: scaleX(-1);
  -ms-transform: scaleX(-1);
  }
  .glyphicon.glyphicon-log-out {
    font-size: 20px;
}
</style>
<div class="panel panel-default">
<% if @over_5 %>
 <%= link_to 'Show All', '?m=all', class: 'btn btn-link pull-right' %>
<% end %>
<%= link_to '<i class="glyphicon glyphicon-log-out icon-flipped"></i>'.html_safe,
'/conversations', { :class => 'tooltips, btn btn-link', 'data-toggle' => 'tooltip',
   'data-placement' => 'right', :title => 'Back To Inbox' } %>
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>
 <% @messages.each do |message| %>
  <% if message.body %>
   <% user = User.find(message.user_id) %>
   <div class="item">
<div class="panel-heading">
       <div class="header"><strong><%= user.email %> </strong><%= message.message_time %></div>
      <div class="list">
       <div class="item">
        <i class="right triangle icon"></i>
        <%= message.body %>
      </div>
    </div>
   </div>
 </div>
 <% end %>
<% end %>
</div>
</div>
<div class="col-md-10 col-md-offset-1">
<%= form_for [@conversation, @message] do |f| %>
<div class="form-group">
  <%= f.text_area :body, class: "form-control" %>
</div>
  <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
<div class="form-group">
  <%= f.submit "Send Reply", class: "form-control btn btn-primary" %>
</div>
<% end %>
</div>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p>
	<%= @content %>
	<br>
	You can find the source code for this website <a href=" https://github.com/rails-decal/fa19-proj2-team-b">here</a>.
</p>

app/views/posts/edit.html.erb
<br>
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area(:body, {:class => 'form-control'}) %>	
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %>

app/views/posts/index.html.erb
<br>
<h1>Social Network</h1>

<% @posts.each do |post| %>
	<div class="well">
		<div style = "margin: 30px;
									border-radius: 10px;
  								border: 2px solid grey;" 
				class="container">
			<h3><%= post.title %></h3>
			<h6>User: <%= post.user.username %></h6>
			<p><%= post.body %></p>
			
			<p> <% if not post.photo.attachment.nil? %>
          			<%= image_tag post.photo, style: 'max-width: 500px' %>
        		<% end %>
        	</p>
        	
			<%= link_to "Dislike (#{post.users_disliked.length})", dislike_path(post), method: :patch %>
			<%= link_to "Read more", post_path(post), :class =>
				'btn btn-outline-secondary btn-light' %>
			<p></p>
		</div>
<% end %>

<div id = "news">
  <p>
    <center>
      <a class="twitter-timeline" data-width="1000" data-height="700" data-theme="light" data-link-color="#19CF86" href="https://twitter.com/social_team_b/lists/news?ref_src=twsrc%5Etfw">News</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </center>
  </p>
</div>

app/views/posts/new.html.erb
<br>
<h1>Add Post</h1>
<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area(:body, {:class => 'form-control'}) %>	
	</p>
	
	<p>
		<%= f.file_field :photo, accept: "image/png,image/gif,image/jpeg" %>
	</p> 
	
	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %>

app/views/posts/show.html.erb
<br>
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>
User:
<%= @post.user.username %>
<br>
<br>
<% if current_user != nil %>

	<% if @post.user.id == current_user.id %>
	<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-light'%>
	<%= link_to "Delete", post_path(@post), 
							method: :delete,
							data: {confirm: 'Do you want to delete this post?'},
							:class => 'btn btn-danger' %>

	<hr>
	<% end %>
<% end %>

<%= render 'comments/comments' %>
<%= render 'comments/form' %>